services:
  - type: web
    name: haitech-zalo-bot
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: ZALO_SESSION_JSON
        sync: false
